[functions]
 external_node_modules = ["express"]
 
  
[dev]
  publish = "dist"

[build] 
  functions = "functions"

[[redirects]]
  force = true
  from = "*"
  status = 200
  to = "/.netlify/functions/todosServer/:splat"